//
//  ChatMessage.swift
//  ChatUI
//
//  Created by Basawaraj on 16/03/16.
//  Copyright © 2016 Basawaraj. All rights reserved.
//

import UIKit

enum EventType : UInt {
    
    /// Unknown event.
    case Unknown       = 0,
    
    /// Member (agent) join event.
    MemberJoin         = 1,
    
    /// Member (agent) leave event.
    MemberLeave        = 2,
    
    /// Chat system message event notifying of visitors in the queue.
    SystemMessage      = 3,
    
    /// Chat message generated by a trigger event.
    TriggerMessage     = 4,
    
    /// Chat message from an agent.
    AgentMessage       = 5,
    
    /// Chat message from the visitor.
    VisitorMessage     = 6,
    
    /// Visitor file upload.
    VisitorUpload      = 7,
    
    /// Agent file upload.
    AgentUpload        = 8,
    
    /// Chat rating event.
    TypeRating         = 9,
    
    /// Chat rating comment event.
    RatingComment      = 10
}

enum MessageType : String {
    
    /// Text.
    case Text     = "Text",
    
    /// Image.
    Image         = "Image",
    
    /// Video.
    Video         = "Video",
    
    /// Audio
    Audio         = "Audio"
    
}



class ChatMessage: NSObject {

    var ticketId: String?
    var senderId: String?
    var msgId: String?
    var displayName: String?
    var avatarUrl: String?
    var eventType: UInt?
    var msgType: String?
    var msgBody: String?
    var timeStamp: NSDate?
    var agentId: String?
    var vendorId: String?
    var mediaFileURL: String?
    var isUploaded: Bool?
    var thumbnailURL: String?
    
}
